Correct 'AxesSubplot' error
Needed to prevent following error when using the subplotwithcolorbar function:
TypeError: 'AxesSubplot' object does not support indexing